type = "javascript"

name = "CHANGE_ME"
account_id = "44321e1b7fbd29b56b65c1890a3bbee2"
compatibility_date = "2022-11-03"

kv_namespaces = []

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "./index.mjs"
dir = "dist"

[miniflare]
kv_persist = true